version: '3.9'

services:
  vip-ecommerce:
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'vip_ecommerce'
    ports:
      - 3306:3306
volumes:
  db_data: {}
